=== k336699k/Support/support-dba/dbxsd/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="support_test">
	<xsd:import namespace="support_test" schemaLocation="support_test.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="users" type="dflt:users__type" />
				<xsd:element name="topics" type="dflt:topics__type" />
				<xsd:element name="inquiries" type="dflt:inquiries__type" />
				<xsd:element name="customers" type="dflt:customers__type" />
				<xsd:any namespace="support_test" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== k336699k/Support/support-dba/src/test/resources/ita/support/dba/dao/admin/impl/inquiry/CRUDInquiryTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="dbxsd/dataset.xsd">

     <topics topic_id="1" name="1" />
     
     <topics topic_id="2" name="1" />
     
     <topics topic_id="3" name="1" />
	
	<customers custmer_id="1" name="1" phone="1" phone_model="1" />
	
	
	<inquiries inquiry_id="1" create_date="2016-05-03" description="10" rezalt="1" customer_id="1"
	topic_id="1" />
	
  <inquiries inquiry_id="2" create_date="2016-04-02" description="10" rezalt="1" customer_id="1"
	topic_id="1" />
	
	<inquiries inquiry_id="3" create_date="2016-04-02" description="10" rezalt="1" customer_id="1"
	topic_id="3" />
     
</dataset>
